<p class="switcher"><label for="area_switcher"><?php echo $this->__('Area:') ?></label>
<select name="area_switcher" id="area_switcher" onchange="switchArea(this);">
  <?php foreach ($this->getOptions() as $option): ?>
    <option value="<?php echo $option ?>" <?php echo $this->isSelected($option) ?>><?php echo $option ?></option>
  <?php endforeach; ?>
</select>
</p>
<script type="text/javascript">
    function switchArea(obj) {
        var areaParam = 'area/' + obj.value + '/';
        setLocation('<?php echo $this->getSwitchUrl() ?>' + areaParam);
    }
</script>
